// Code generated by MockGen. DO NOT EDIT.
// Source: transport/stream/writer.go
//
// Generated by this command:
//
//	mockgen -source=transport/stream/writer.go -destination=transportmock/streammock/writer.go -package=streammock -typed
//

// Package streammock is a generated GoMock package.
package streammock

import (
	context "context"
	reflect "reflect"

	stream "github.com/tesserical/geck/transport/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockWriter) Write(ctx context.Context, name string, message stream.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, name, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockWriterMockRecorder) Write(ctx, name, message any) *MockWriterWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWriter)(nil).Write), ctx, name, message)
	return &MockWriterWriteCall{Call: call}
}

// MockWriterWriteCall wrap *gomock.Call
type MockWriterWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWriterWriteCall) Return(arg0 error) *MockWriterWriteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWriterWriteCall) Do(f func(context.Context, string, stream.Message) error) *MockWriterWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWriterWriteCall) DoAndReturn(f func(context.Context, string, stream.Message) error) *MockWriterWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteBatch mocks base method.
func (m *MockWriter) WriteBatch(ctx context.Context, name string, messages []stream.Message) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatch", ctx, name, messages)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteBatch indicates an expected call of WriteBatch.
func (mr *MockWriterMockRecorder) WriteBatch(ctx, name, messages any) *MockWriterWriteBatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatch", reflect.TypeOf((*MockWriter)(nil).WriteBatch), ctx, name, messages)
	return &MockWriterWriteBatchCall{Call: call}
}

// MockWriterWriteBatchCall wrap *gomock.Call
type MockWriterWriteBatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWriterWriteBatchCall) Return(arg0 int, arg1 error) *MockWriterWriteBatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWriterWriteBatchCall) Do(f func(context.Context, string, []stream.Message) (int, error)) *MockWriterWriteBatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWriterWriteBatchCall) DoAndReturn(f func(context.Context, string, []stream.Message) (int, error)) *MockWriterWriteBatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
